spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc\:mysql\://localhost\:3306/spring_eventms
spring.datasource.username=root
spring.datasource.password=
 

spring.main.allow-bean-definition-overriding=true

